export const LIST_IDS_WLS = [
    'USTEL', 'UNTAL', 'UNRM', 'UNOT', 'UNEMB', 'UNCON', 'UKHOME', 'UKFCAW', 'UKBISI', 'TRA221', 'SECOSP',
    'SECOSA', 'SECOOT', 'SECOEM', 'RUFFMF', 'RUFFMD', 'RUCBR', 'RBASA', 'QNTER', 'OSFITE', 'OSFISA',
    'OSFIOT', 'OFHFSR', 'OFCSSI', 'OFCISA', 'OFCFSE', 'OFC561', 'OFACTR', 'OFACSD', 'OFACOT', 'OFACNS',
    'OFACCS', 'OCCUNB', 'NZPOUN', 'NZPONO', 'NLSAN', 'MPSTE', 'METIEN', 'METIE', 'MASTER', 'MASOT', 'JAFISA',
    'ISNSA', 'IMODIO', 'HMTOT', 'HMTINV', 'HMTASS', 'HKMASA', 'HKMAOT', 'GAOIR', 'FRNAT', 'FJMB', 'FIN311',
    'FCSFIA', 'FBIWAN', 'FATFNC', 'FATFJ', 'EUSSI', 'EURM', 'EUOTTE', 'EUOT', 'EUEMB', 'EUCON', 'DOSSST',
    'DOSISA', 'DOSCUB', 'DJ', 'DFATRU', 'DFATOT', 'DFATCO', 'DFAITS', 'DFAITJ', 'DFAITF', 'DFAITE', 'DDTCDP',
    'CSSFSA', 'CSSFOT', 'CIMAOT', 'CCDI', 'CAPTA', 'CANPUB', 'CALICA', 'CAATSA', 'BISOT', 'BISDPL', '13808', '13599', '13566'
];

export const IC_TENANT_PROPERTIES = {
    interdiction_mode: 'PREVENTION',
    'compliance-screening_fatf16-compliance_interdiction_mode': 'PREVENTION',
    'compliance-screening_transaction-screening_interdiction_mode': 'PREVENTION',
    sp_interdiction_mode: 'PREVENTION',
    UserBehaviorMonitoring_interdiction_mode: 'PREVENTION',
    AML: 'true',
    CardFraud: 'true',
    CheckFraud: 'true',
    'compliance-screening_fatf16-compliance': 'true',
    ECM: 'true',
    IEF: 'true',
    'include.incident.data.in.score.response.api': 'false',
    NPF: 'true',
    sanction: 'true',
    SAR: 'false',
    'secure-payments_ach': 'true',
    'secure-payments_bulk-fin': 'true',
    'secure-payments_bulk-iso20022': 'true',
    'secure-payments_fedwire': 'true',
    'secure-payments_ml_bulk_fin': 'true',
    'secure-payments_ml_bulk_iso20022': 'true',
    'secure-payments_ml_supervised_ach': 'true',
    'secure-payments_ml_supervised_bulk_iso20022': 'true',
    'secure-payments_ml_supervised_fedwire': 'true',
    'secure-payments_ml_supervised_swift': 'true',
    'secure-payments_ml_swift': 'true',
    'secure-payments_ml_unsupervised_ach': 'true',
    'secure-payments_ml_unsupervised_fedwire': 'true',
    'secure-payments_ml_unsupervised_sic': 'true',
    'secure-payments_offline-swift': 'true',
    'secure-payments_sic': 'true',
    WFS: 'true',
    WFS_ml_supervised_wpf: 'true',
    WFS_ml_wpf: 'true',
    'compliance-screening_transaction-screening': 'true'
};
